//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int ID { get; set; }
        public string UName { get; set; }
        public string PWord { get; set; }
        public string ForgetQuery { get; set; }
        public string ForgetAnd { get; set; }
        public int IsDelete { get; set; }
    }
}
