//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LLProjectEntities : DbContext
    {
        public LLProjectEntities()
            : base("name=LLProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<ItemInfo> ItemInfoes { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<StockIN> StockINs { get; set; }
    }
}
