//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SID { get; set; }
        public Nullable<int> CusName { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string Qutantity { get; set; }
        public string Price { get; set; }
        public string TotalAmount { get; set; }
        public string Paid { get; set; }
        public string Balance { get; set; }
        public string Date { get; set; }
        public int IsDelete { get; set; }
    }
}
